#####
# FSM params 
#####
fsm:
  # waypoint_type: 1 for manual publishing of single goals, 2 for sending multiple waypoints 
  waypoint_type: 2
  # thresh_replan_time: Replanning period (1/frequency)
  thresh_replan_time: 0.1
  # thresh_no_replan_meter: Replan only if current position and local target exceeds this parameter 
  thresh_no_replan_meter: 0.25
  # planning_horizon: Distance to plan for local target. Always set to 1.5 times greater than sensing horizon
  planning_horizon: 10.0
  emergency_time: 1.0
  fail_safe: true

  # pub_state_freq: Frequency to publish the state
  pub_state_freq: 10.0
  # pub_heartbeat_freq: Frequency to publish planner heartbeat
  pub_heartbeat_freq: 10.0
  # pub_heartbeat_freq: Timeout for TF lookup
  tf_lookup_timeout: 60.0

#####
# Mapping params
#####
grid_map:
# global_frame: "world"
  map_size_x: 80.0
  map_size_y: 80.0
  map_size_z: 20.0
  local_map_size_x: 1.5 
  local_map_size_y: 1.5 
  local_map_size_z: 2.5 

  sensor/max_range: 5.0
  ground_height: 0.0

  occ_grid/resolution: 0.1 
  occ_grid/inflation: 0.0
  filter/downsample_cloud: false 
  filter/depth_stride: 4 
  filter/voxel_size: 0.1

  # camera intrinsic parameters 
  k_depth_scaling_factor: 1000.0
  # camera extrinsic parameters 
  camera_to_body/roll: 90.0
  camera_to_body/pitch: 180.0
  camera_to_body/yaw: 90.0
  camera_to_body/t_x: 0.0
  camera_to_body/t_y: 0.0
  camera_to_body/t_z: 0.0

#####
# Manager params 
#####
manager: 
  # When changing maximum velocity and acceleration, make sure to change those on the optimization params too
  max_vel: 1.5
  max_acc: 6.0
  # polyTraj_piece_length: distance between adjacent spline control points
  polyTraj_piece_length: 1.5
  # feasibility_tolerance: permitted ratio of vel/acc exceeding limits 
  feasibility_tolerance: 0.05 
  planning_horizon: 7.5
  use_distinctive_trajs: false

#####
# Optimization params
#####
optimization:
  constraint_points_perPiece: 10
  weight_obstacle: 10000.0 
  weight_obstacle_soft: 5000.0 
  weight_swarm: 50000.0 
  weight_feasibility: 10000.0 
  weight_sqrvariance: 10000.0 
  weight_time: 10.0 
  obstacle_clearance: 0.35 
  obstacle_clearance_soft: 0.5 
  swarm_clearance: 0.4 
  max_vel: 1.5
  max_acc: 6.0
  max_jer: 20.0