# Safety bounding box
traj_server/enable_safety_box: false
traj_server/pos_limit/min_x: -5.5
traj_server/pos_limit/min_y: -5.5
traj_server/pos_limit/min_z: -0.5
traj_server/pos_limit/max_x: 5.5
traj_server/pos_limit/max_y: 5.5
traj_server/pos_limit/max_z: 3.0

# Frequency for timers
traj_server/pub_cmd_freq: 25.0
traj_server/state_machine_tick_freq: 50.0
traj_server/takeoff_height: 0.75
