#####
# Back-end params
#####
back_end:
  # planner_frequency: 30.0
  # planning_horizon: How far ahead to plan [m]
  planning_horizon: 30.0
  # num_replan_retries: Number of times for back-end to retry
  num_replan_retries: 10

#####
# Mapping params
#####
grid_map:
  global_frame: "world"
  uav_origin_frame: "world"

  map_size_x: 80.0
  map_size_y: 80.0
  map_size_z: 20.0
  local_map_size_x: 1.5 
  local_map_size_y: 1.5 
  local_map_size_z: 2.5 

  sensor/max_range: 5.0
  ground_height: 0.0

  occ_grid/resolution: 0.1
  occ_grid/inflation: 0.2
  filter/downsample_cloud: false 
  filter/depth_stride: 4 
  filter/voxel_size: 0.1

  # camera intrinsic parameters 
  k_depth_scaling_factor: 1000.0
  # camera extrinsic parameters 
  camera_to_body: 
    roll: 90.0
    pitch: 180.0
    yaw: 90.0
    t_x: 0.0
    t_y: 0.0
    t_z: 0.0

#####
# Manager params 
#####
manager: 
  # When changing maximum velocity and acceleration, make sure to change those on the optimization params too
  max_vel: 1.5
  max_acc: 6.0 # 8 newtons max, for 0.3g. 8/0.3 = 26.67
  # polyTraj_piece_length: distance between adjacent spline control points
  polyTraj_piece_length: 1.5
  # feasibility_tolerance: permitted ratio of vel/acc exceeding limits 
  feasibility_tolerance: 0.05 
  planning_horizon: 30
  use_distinctive_trajs: false

#####
# Optimization params
#####
optimization:
  constraint_points_perPiece: 5
  weight_obstacle: 10000.0 
  weight_obstacle_soft: 5000.0 
  weight_swarm: 50000.0 
  weight_feasibility: 10000.0
  weight_sqrvariance: 10000.0 
  weight_time: 10.0 
  # obstacle_clearance: 0.35 
  # obstacle_clearance_soft: 0.5 
  swarm_clearance: 0.4 
  max_vel: 1.5
  max_acc: 6.0
  max_jer: 20.0

# optimization:
#   constraint_points_perPiece: 5
#   weight_obstacle: 10000.0 
#   weight_obstacle_soft: 5000.0 
#   weight_swarm: 50000.0 
#   weight_feasibility: 10000.0 
#   weight_sqrvariance: 10000.0 
#   weight_time: 10.0 
#   weight_formation: 100 
#   obstacle_clearance: 0.35 
#   obstacle_clearance_soft: 0.5 
#   swarm_clearance: 0.4 
#   max_vel: 1.5
#   max_acc: 6.0
#   max_jer: 20.0
