#####
# Front-end params
#####
front_end:
  planner_frequency: 10.0
  goal_tolerance: 0.1       # in [m]
  max_iterations: 99999999  
  debug_viz: true          # If true, publish visualization for debugging
  tie_breaker: 1.0001       # Tie breaker as weight for f-cost (cost-to-go)

sfc:
  max_iterations: 100     # Corresponds to maximum number of spheres
  debug_viz: false        # If true, publish visualization for debugging
  # Sampling
  max_sample_points: 1000 # Maximum sample points for candidate sphere
  mult_stddev_x: 0.1      # A higher value leads to clustering of spheres around previous spheres
  W_cand_vol: 1           # Weight for candidate sphere volume
  W_intersect_vol: 5      # Weight for volume of intersection between spheres
  # Criteria for valid spheres
  min_sphere_vol: 0.1 # (m^3) Minimum volume of sphere
  max_sphere_vol: 1000.0 # (m^3) Maximum allowed sphere volume
  min_sphere_intersect: 0.05 # (m^3) Minimum volume of sphere intersection

  # Initial time allocation
  avg_vel: 1.5 # Average velocity (m/s) used for estimating initial time allocation
  max_vel: 3.0 # Maximum velocity (m/s)

#####
# Mapping params
#####
grid_map:
  # global_frame: "world"
  map_size_x: 80.0
  map_size_y: 80.0
  map_size_z: 20.0
  local_map_size_x: 1.5 
  local_map_size_y: 1.5 
  local_map_size_z: 2.5 

  sensor/max_range: 5.0
  ground_height: 0.0

  occ_grid/resolution: 0.1
  occ_grid/inflation: 0.2
  filter/downsample_cloud: false 
  filter/depth_stride: 4 
  filter/voxel_size: 0.1

  # camera intrinsic parameters 
  k_depth_scaling_factor: 1000.0
  # camera extrinsic parameters 
  camera_to_body: 
    roll: 90.0
    pitch: 180.0
    yaw: 90.0
    t_x: 0.0
    t_y: 0.0
    t_z: 0.0
