#####
# Front-end params
#####
front_end:
  planner_frequency: 10.0
  goal_tolerance: 0.1 # in [m]
  max_iterations: 1000 

sfc:
  max_iterations: 50
  sfc_max_sample_points: 1000
  mult_stddev_x: 0.1 # A higher value leads to worse
  W_cand_vol: 1
  W_intersect_vol: 5

#####
# Mapping params
#####
grid_map:
  # global_frame: "world"
  map_size_x: 80.0
  map_size_y: 80.0
  map_size_z: 20.0
  local_map_size_x: 1.5 
  local_map_size_y: 1.5 
  local_map_size_z: 2.5 

  sensor/max_range: 5.0
  ground_height: 0.0

  occ_grid/resolution: 0.1
  occ_grid/inflation: 0.2 
  filter/downsample_cloud: false 
  filter/depth_stride: 4 
  filter/voxel_size: 0.1

  sensor_queue_size: 5

  # camera intrinsic parameters 
  k_depth_scaling_factor: 1000.0
  # camera extrinsic parameters 
  camera_to_body: 
    roll: 90.0
    pitch: 180.0
    yaw: 90.0
    t_x: 0.0
    t_y: 0.0
    t_z: 0.0
