
# flight mission
traj_server:
  takeoff_height: 1.2

mission:
  ##------ MPC initial pose ----##
  initial_position: [0.0, 0.0, 1.2]
  initial_ori_euler: [0.0, 0.0, 0.0]

  ##------ gate pose ----##
  gate_position: [1.0, 0.0, 0.8]
  gate_ori_euler: [0.0, 0.0, 0.0]

  ##------ goal pose ----##
  goal_position: [2.0, 0.0, 1.2]
  mission/goal_ori_euler: [0.0, 0.0, 0.0]


# MPC parameters
learning_agile:
  ##------ MPC problem parameters---## 
  horizon: 10
  dt: 0.1

  ##------ traversing parameters ---##
  max_traverse_weight: 70 #70
  traverse_time: 2

  ##------ safety parameters  ------##
  no_solution_flag_t_thresh: 0.1
  
  
  ##------ model parameters --------##
  # 1.7268 N is based on the hover throttle: 0.29
  # drone mass: 0.248kg, g: 9.81m/s^2 weight: 0.248*9.81 = 2.43368N
  # hover throttle: 0.29, thrust: 0.29*max_thrust =2.43368N
  # max_thrust = 2.43368/0.29 = 8.4N
  # single_motor_max_thrust = 8.4/4 = 2.1N
  single_motor_max_thrust: 2.0 #2.1334185 #N
  
  ##------ constraints parameters --##
  # position constraints
  pos_bound: 5 #m

  # velocity constraints
  linear_vel_bound: 3.0 #m/s

  # angular velocity constraints
  angular_vel_bound: 1.57 #rad/s


  # miscellaneous parameters 
  pred_traj_vis: true