
#####
# Navigator params
#####
# drone_id: 0       # Set in launch file
# debug_planning: false       # Set in launch file
planner_frequency: 2.0        # [Hz]
safety_check_frequency: 20.0  # [Hz]
goal_tolerance: 0.3           # [m] 
time_to_col_threshold: 0.2    # [s] Threshold for seconds to collision.

##### Front-end params
front_end:
  max_iterations: 99999  
  debug_viz: true          # If true, publish visualization for debugging
  tie_breaker: 1.0001       # Tie breaker as weight for f-cost (cost-to-go)
  cost_function_type: 0    # Type of cost function to use 

##### Safe flight corridor
sfc:
  max_iterations: 100     # Corresponds to maximum number of spheres
  debug_viz: true        # If true, publish visualization for debugging
  # Sampling
  max_sample_points: 300 # Maximum sample points for candidate sphere
  # standard deviation: remember 68–95–99.7 rule
  # mult_stddev_x: 0.1      # if mult_stddev_x is too high, the spheres cannot round corners and generate loads of spheres around the same area around corners
  # mult_stddev_y: 0.3      # 
  # mult_stddev_z: 0.3      # 

  mult_stddev_x: 0.75      # 
  mult_stddev_y: 0.55      # 
  mult_stddev_z: 0.55      # 

  # mult_stddev_x: 1.5      # 
  # mult_stddev_y: 1.0      # 
  # mult_stddev_z: 1.0      # 

  W_cand_vol: 5         # Weight for candidate sphere volume
  W_intersect_vol: 10    # Weight for volume of intersection between spheres
  W_progress: 0        # Weight for progress along guide path

  # Criteria for valid spheres
  min_sphere_vol: 0.01 # (m^3) Minimum volume of sphere
  max_sphere_vol: 9999999999999.0 # (m^3) Maximum allowed sphere volume

  # Initial time allocation
  # avg_vel: 1.5 # Average velocity (m/s) used for estimating initial time allocation
  max_vel: 0.5 # Maximum velocity (m/s)
  max_acc: 3.0 # Maximum velocity (m/s)

  # SFC Buffer 
  spherical_buffer: 0.125 # (m) Reduce spherical SFCs by this fixed amount to increase buffer from obstacles

##### Back-end 
back_end:
  num_replan_retries: 10 # Number of times for back-end to retry

##### Optimization params
optimization:
  constraint_points_perPiece: 10
  weight_obstacle: 10000.0 
  weight_obstacle_soft: 5000.0 
  weight_swarm: 50000.0 
  weight_feasibility: 10000.0
  weight_sqrvariance: 10000.0 
  weight_time: 10.0 
  # obstacle_clearance: 0.35 
  # obstacle_clearance_soft: 0.5 
  swarm_clearance: 0.4 
  max_vel: 1.5
  max_acc: 6.0
  max_jer: 20.0

##### Mapping params
grid_map:
  # global_frame: "world"
  map_size_x: 80.0
  map_size_y: 80.0
  map_size_z: 20.0
  local_map_size_x: 1.5 
  local_map_size_y: 1.5 
  local_map_size_z: 2.5 

  ground_height: 0.0

  occ_grid:
    resolution: 0.1
    inflation: 0.2
  filter:
    downsample_cloud: false 
    depth_stride: 4 
    voxel_size: 0.1

  # For visualizing collision with static obstacles
  collision_check:
    warn_radius: 0.225
    fatal_radius: 0.14

  sensor/max_range: 5.0

  # camera intrinsic parameters 
  k_depth_scaling_factor: 1000.0
  # camera extrinsic parameters 
  camera_to_body: 
    roll: 90.0
    pitch: 180.0
    yaw: 90.0
    t_x: 0.0
    t_y: 0.0
    t_z: 0.0
