
#####
# Navigator params
#####
# drone_id: 0       # Set in launch file
# debug_planning: false       # Set in launch file
planner_frequency: 5.0        # [Hz]
safety_check_frequency: 20.0  # [Hz]
goal_tolerance: 0.3           # [m] Tolerance for goal to have been reached
time_to_col_threshold: 0.2    # [s] Threshold for seconds to collision.
receding_horizon_planning_dist: 7.5        # [m] Receding horizon planning

##### Set planner types
front_end/planner_type: 1         # 0: ASTAR, 1: JPS_AND_DMP
sfc/planner_type: 0               # 0: SPHERICAL, 1: POLYTOPE
back_end/planner_type: 0          # 0: SSFC, 1: EGO

##### Front-end params
front_end:
  a_star:
    max_iterations: 9999  
    debug_viz: true           # If true, publish visualization for debugging
    tie_breaker: 1.00001      # Tie breaker as weight for f-cost (cost-to-go)
    cost_function_type: 0     # [AStar] Type of cost function to use 

  jps:
    planner_verbose: false      # If true, print debug from planner
    interpolate: true           # Interpolate JPS (necessary for spherical safe flight generation)
    use_dmp: false               # 
    dmp_search_radius: 0.4      # DMP Search radius
    dmp_potential_radius: 0.4   # DMP radius of distance field (Value has significant effect on runtime)
    dmp_collision_weight: 0.1   # DMP Collision weight 
    dmp_heuristic_weight: 0.0   # DMP Heuristic weight
    # dmp_search_radius: 0.75      # DMP Search radius
    # dmp_potential_radius: 0.4   # DMP radius of distance field (Value has significant effect on runtime)
    # dmp_collision_weight: 0.25   # DMP Collision weight 
    # dmp_heuristic_weight: 0.0   # DMP Heuristic weight
    dmp_pow: 1    # DMP power index 

##### Safe flight corridor
sfc:
  spherical: 
    max_iterations: 60     # Corresponds to maximum number of spheres
    debug_viz: true        # If true, publish visualization for debugging
    # Sampling
    max_sample_points: 50 # Maximum sample points for candidate sphere
    # standard deviation: remember 68–95–99.7 rule
    # mult_stddev_x: 0.1      # if mult_stddev_x is too high, the spheres cannot round corners and generate loads of spheres around the same area around corners
    # mult_stddev_y: 0.3      # 
    # mult_stddev_z: 0.3      # 

    mult_stddev_x: 0.15      # 
    mult_stddev_y: 0.3      # 
    mult_stddev_z: 0.3      # 

    W_cand_vol: 5         # Weight for candidate sphere volume
    W_intersect_vol: 10    # Weight for volume of intersection between spheres
    W_progress: 0        # Weight for progress along guide path

    # Criteria for valid spheres
    min_sphere_vol: 0.001 # (m^3) Minimum volume of sphere
    max_sphere_vol: 99999.9 # (m^3) Maximum allowed sphere volume

    # Initial time allocation
    # max_vel: 3.0 # Maximum velocity (m/s)
    # max_acc: 12.0 # Maximum velocity (m/s)
    # avg_vel: 1.5 # Average velocity (m/s) used for estimating initial time allocation

    time_allocation_type: 1 #  0: Max vel assignment, 1: Trapezoidal assignment
    max_vel: 5.0 # Maximum velocity (m/s)
    max_acc: 20.0 # Maximum acceleration (m/s^2)

    # SFC Buffer 
    spherical_buffer: 0.175 # (m) Reduce spherical SFCs by this fixed amount to increase buffer from obstacles

  poly:
    max_iterations: 60
    debug_viz: true
    poly_max: 10
    cvx_decomp_type: 2
    num_expansion_itr: 60

##### Back-end 
back_end: 
  num_replan_retries: 5 # Number of times for back-end to retry
  ego:
    segment_length: 1.5 # Length of one segment i.e. distance between adjacent spline control points

##### Optimization params
optimization:
  num_cstr_pts_per_seg: 5 # Number of constraint points per trajectory segment i.e. discretization.
  # Weights
  weight_sph_bounds: 10000.0
  weight_swarm: 50000.0 
  weight_feasibility: 10000.0
  weight_sqrvariance: 10000.0 
  weight_time: 10.0 
  swarm_clearance: 0.4 
  max_vel: 5.0 # Maximum velocity (m/s)
  max_acc: 20.0 # Maximum acceleration (m/s^2)

  # EGO params
  weight_obstacle: 10000.0 
  obstacle_clearance: 0.35 

##### Mapping params
grid_map:
  # global_frame: "world"
  map_size_x: 50.0
  map_size_y: 50.0
  map_size_z: 20.0
  # map_size_x: 20.0
  # map_size_y: 20.0
  # map_size_z: 20.0
  local_map_size_x: 15.5
  local_map_size_y: 15.5 
  local_map_size_z: 5.0

  ground_height: 0.0

  occ_grid:
    resolution: 0.1
    inflation: 0.2
  filter:
    downsample_cloud: false 
    depth_stride: 4 
    voxel_size: 0.1

  # For visualizing collision with static obstacles
  collision_check:
    warn_radius: 0.225
    fatal_radius: 0.14

  sensor/max_range: 5.0

  # camera intrinsic parameters 
  k_depth_scaling_factor: 1000.0
  # camera extrinsic parameters 
  camera_to_body: 
    roll: 90.0
    pitch: 180.0
    yaw: 90.0
    t_x: 0.0
    t_y: 0.0
    t_z: 0.0
