##### Mapping params
grid_map:
  global_map:
    size_x: 50.0
    size_y: 50.0
    size_z: 20.0
  local_map:      #local_map parameters must consider the "receding_horizon_planning_dist"!
    # size_x: 15.5
    # size_y: 15.5 
    # size_z: 5.0
    size_x: 17.0
    size_y: 17.0
    size_z: 5.0
    update_frequency: 15.0
    viz_frequency: 10.0
    # build_kdtree_frequency: 30.0

  occ_map:
    resolution: 0.1
    inflation: 0.2
    ground_height: 0.0
    max_range: 30.0

  # For visualizing collision with static obstacles
  collision_check:
    warn_radius: 0.225
    fatal_radius: 0.14

  # camera extrinsic parameters 
  camera_to_body: 
    # roll: 90.0
    # pitch: 180.0
    # yaw: 90.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0 
    t_x: 0.0 # x translation
    t_y: 0.0
    t_z: 0.0


#####
# Navigator params
#####
# debug_planning: false     # Set in launch file. Used to allow certain topics for debugging planning algorithms
# verbose_planning: true     # Print out planning times

goal_tolerance: 0.2                     # [m] Tolerance for goal to be considered reached
time_to_col_threshold: 0.2              # [s] Threshold for seconds to collision.
receding_horizon_planning_dist: 7.5     # [m] Receding horizon planning
receding_horizon_corridor_dist: 3.0     # [m] Receding horizon corridor

safety_check_frequency: 20.0            # [Hz] Timer thread for checking safety of trajectory
heartbeat_frequency: 20.0               # [Hz] Frequency to indicate if planner is still alive

##### Set planner types
front_end/planner_type: 1         # 0: ASTAR, 1: JPS_AND_DMP
sfc/planner_type: 1               # 0: SPHERICAL, 1: POLYTOPE
back_end/planner_type: 2          # 0: SSFC, 1: EGO, 2: POLY

##### Front-end params
front_end:
  planner_frequency: 5.0        # [Hz] Front-end planning frequency

  a_star:
    max_iterations: 9999  
    debug_viz: true           # If true, publish visualization for debugging
    tie_breaker: 1.00001      # Tie breaker as weight for f-cost (cost-to-go)
    cost_function_type: 0     # [AStar] Type of cost function to use 

  jps:
    planner_verbose: false      # If true, print debug from planner
    interpolate: true           # Interpolate JPS (necessary for spherical safe flight generation)
    use_dmp: false               # 
    dmp_search_radius: 0.4      # DMP Search radius
    dmp_potential_radius: 0.4   # DMP radius of distance field (Value has significant effect on runtime)
    dmp_collision_weight: 0.1   # DMP Collision weight 
    dmp_heuristic_weight: 0.0   # DMP Heuristic weight
    # dmp_search_radius: 0.75      # DMP Search radius
    # dmp_potential_radius: 0.4   # DMP radius of distance field (Value has significant effect on runtime)
    # dmp_collision_weight: 0.25   # DMP Collision weight 
    # dmp_heuristic_weight: 0.0   # DMP Heuristic weight
    dmp_pow: 1                  # DMP power index 

##### Back-end 
back_end: 
  # planner_frequency: 1.0       # [Hz]

  num_replan_retries: 2 # Number of times for back-end to retry
  ego:
    segment_length: 1.5 # Length of one segment i.e. distance between adjacent spline control points

##### Optimization params
optimization:
  num_cstr_pts_per_seg: 5 # Number of constraint points per trajectory segment i.e. discretization.
  # Weights
  weight_sph_bounds: 1000.0
  weight_swarm: 50000.0 
  weight_feasibility: 10000.0
  weight_sqrvariance: 10000.0 
  weight_time: 10.0 
  swarm_clearance: 0.4 
  max_vel: 5.0 # Maximum velocity (m/s)
  max_acc: 20.0 # Maximum acceleration (m/s^2)

  # EGO params
  weight_obstacle: 10000.0 
  obstacle_clearance: 0.35 

  barrier:
    alpha: 2.0
    buffer: 0.4
    opt_weight: 0.0
