filename: vicon_obs3
polar_obs: 0 # Number of cylinder obstacles
circle_obs: 0 # Number of hoops
seed: 1

map:
  inter_obstacle_clearance: 0.8 # Minimum separation distance between center of obstacle primitives
  resolution: 0.1
  x_size: 5.6            # size of map, obstacles will only be populated within the map size bounds
  y_size: 5.6            # size of map, obstacles will only be populated within the map size bounds
  z_size: 2.5             # size of map, obstacles will only be populated within the map size bounds
  enable_floor: true      # Add point cloud floor plane (Set at z = 0.0)
  enable_ceiling: true    # Add point cloud ceiling plane (Set at z = 2.5)
  enable_walls: true      # Add boundary walls defined by "x_size" and "y_size"

obstacle:
  cylinder: 
    lower_rad: 0.3  # Cylinder: Smallest radius
    upper_rad: 0.3  # Cylinder: Largest radius
    lower_hei: 3.0  # Cylinder: Lowest height
    upper_hei: 3.0  # Cylinder: Tallest height
  circle:
    radius_l: 7.0   # Circle: Smallest radius
    radius_h: 7.0   # Circle: Biggest radius
    z_l: 7.0        # Circle: Smallest radius
    z_h: 7.0        # Circle: Biggest radius
    theta: 7.0      # Circle
